language: erlang
otp_release:
  - R16B
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - MIX_ENV=test mix do deps.clean -all
  - MIX_ENV=test mix do deps.get
script:
  - mix test
env:
  - MIX_ENV=test
